/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
 * Generated on: 05-Nov-2014 15:22:39
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 29
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2013a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int BL = 29;
const float B[29] = {
  0.0009343012352,  0.01109662466,-0.004983901978, -0.01617116295, 0.008312188089,
   0.006552922539, 0.005379445385,  0.02225745283, -0.05409459025, -0.05289233848,
     0.1352012306,  0.05767413229,  -0.2151846886, -0.02512621321,   0.2488720417,
   -0.02512621321,  -0.2151846886,  0.05767413229,   0.1352012306, -0.05289233848,
   -0.05409459025,  0.02225745283, 0.005379445385, 0.006552922539, 0.008312188089,
   -0.01617116295,-0.004983901978,  0.01109662466,0.0009343012352
};
