/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
 * Generated on: 12-Nov-2014 18:12:34
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 11
 * Denominator Length  : 11
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2013a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int NL = 11;
const float NUM[11] = {
  0.0005674039712,              0,-0.002837019973,              0, 0.005674039945,
                0,-0.005674039945,              0, 0.002837019973,              0,
  -0.0005674039712
};
const int DL = 11;
const float DEN[11] = {
                1,-7.647617488e-16,    3.322425127,-1.572639275e-15,    4.613235474,
  -1.162260705e-15,    3.302992821,-3.460021593e-16,     1.21181345,-3.087173704e-17,
     0.1814741045
};
