/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
 * Generated on: 10-Nov-2014 20:48:40
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 9
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2013a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
#define MWSPT_NSEC 19
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const float NUM[MWSPT_NSEC][3] = {
  {
     0.2247988135,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
     0.2247988135,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
     0.2107877135,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
     0.2107877135,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
     0.2011197209,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
     0.2011197209,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
     0.1954830289,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
     0.1954830289,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
     0.1936335415,              0,              0 
  },
  {
                1,              0,             -1 
  },
  {
                1,              0,              0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1 };
const float DEN[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,   0.4431321919,   0.9240270853 
  },
  {
                1,              0,              0 
  },
  {
                1,  -0.4431321919,   0.9240270853 
  },
  {
                1,              0,              0 
  },
  {
                1,   0.3676424325,   0.7936874628 
  },
  {
                1,              0,              0 
  },
  {
                1,  -0.3676424325,   0.7936874628 
  },
  {
                1,              0,              0 
  },
  {
                1,   0.2629325688,   0.6955939531 
  },
  {
                1,              0,              0 
  },
  {
                1,  -0.2629325688,   0.6955939531 
  },
  {
                1,              0,              0 
  },
  {
                1,    0.137232393,   0.6339101791 
  },
  {
                1,              0,              0 
  },
  {
                1,   -0.137232393,   0.6339101791 
  },
  {
                1,              0,              0 
  },
  {
                1,-1.006860653e-16,   0.6127328873 
  },
  {
                1,              0,              0 
  }
};
