/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
 * Generated on: 11-Nov-2014 13:33:49
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 19
 * Denominator Length  : 19
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2013a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int NL = 19;
const float NUM[19] = {
  6.720268857e-07,              0,-6.04824163e-06,              0,2.419296652e-05,
                0,-5.645025522e-05,              0,8.467538282e-05,              0,
  -8.467538282e-05,              0,5.645025522e-05,              0,-2.419296652e-05,
                0, 6.04824163e-06,              0,-6.720268857e-07
};
const int DL = 19;
const float DEN[19] = {
                1,-6.835531532e-16,    6.287676811,-5.03635499e-15,    17.87677956,
  -1.490253166e-14,    30.09516144,-2.449660788e-14,    33.00340652,-2.559125058e-14,
      24.41615486,-1.729179645e-14,    12.17221737, -7.2863951e-15,    3.939489603,
  -1.744235868e-15,   0.7504983544,-1.805969799e-16,  0.06407766789
};
