/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.1 and the DSP System Toolbox 8.4.
 * Generated on: 15-Nov-2014 13:59:26
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 27
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : fixed
 * Numerator         : s8,9 -> [-2.500000e-01 2.500000e-01)
 * Input             : s16,15 -> [-1 1)
 * Filter Internals  : Full Precision
 *   Output          : s26,24 -> [-2 2)  (auto determined)
 *   Product         : s23,24 -> [-2.500000e-01 2.500000e-01)  (auto determined)
 *   Accumulator     : s26,24 -> [-2 2)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2013a\extern\include\tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int8 filter coefficients.
 */
const int BL = 27;
const char B[27] = {
      0,   -5,    0,    4,    0,    3,    0,  -18,    0,   38,    0,  -56,
      0,   63,    0,  -56,    0,   38,    0,  -18,    0,    3,    0,    4,
      0,   -5,    0
};
